### ISSUE TITLE
No diagnostics found!

### ISSUE THREAD

**Issue by TBBtianbaoboy** [piersolenski/wtf.nvim#10]
That is why?

**Comment by piersolenski** [comment]
The `Wtf` command will show this message if using it on a line or visual selection with no diagnostics, or if there is no LSP attached for the current buffer. Feel free to comment with more information if that's not the case!

**Comment by karismatic-megafauna** [comment]
I'm getting this issue as well!

I believe it's because I am still using CoC to manage my LSPs.

Here is my editor showing a diagnostics:
![image](https://github.com/piersolenski/wtf.nvim/assets/1623740/545335b4-3cda-483d-86a4-df543880c9d5)

![image](https://github.com/piersolenski/wtf.nvim/assets/1623740/a451e3e1-def7-41eb-b6f8-30a93b369f85)

**Comment by piersolenski** [comment]
Unfortunately Wtf works using the native Neovim LSP support and thus does will not work with CoC, it's definitely worth making the switch though!
